# Generated by Django 3.0a1 on 2019-09-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfrozen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articleName',
            field=models.CharField(default='no name', max_length=200),
            preserve_default=False,
        ),
    ]
