# Generated by Django 3.0a1 on 2019-09-16 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unfrozen', '0003_article_articlesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='article',
            old_name='articleAuthor',
            new_name='article_author',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='articleName',
            new_name='article_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='authorEmail',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='authorFullName',
            new_name='author_fullName',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='authorInfo',
            new_name='author_info',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='authorFacebook',
            new_name='author_link',
        ),
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='author',
            name='authorPhoto',
        ),
        migrations.AddField(
            model_name='article',
            name='article_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='author_photo',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TagArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagArticle_article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unfrozen.Article')),
                ('tagArticle_tag_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unfrozen.Tag')),
            ],
        ),
    ]
