# Generated by Django 3.0a1 on 2019-09-15 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorFullName', models.CharField(max_length=200)),
                ('authorInfo', models.TextField()),
                ('authorPhoto', models.ImageField(upload_to='images/authors/')),
                ('authorEmail', models.CharField(max_length=200)),
                ('authorFacebook', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleContent', models.TextField()),
                ('articleDateAdded', models.DateTimeField(verbose_name='date published')),
                ('articleAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unfrozen.Author')),
            ],
        ),
    ]
