# Generated by Django 3.0a1 on 2019-09-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfrozen', '0002_article_articlename'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articleSource',
            field=models.CharField(default='no source', max_length=400),
            preserve_default=False,
        ),
    ]
