# Generated by Django 3.0a1 on 2019-09-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unfrozen', '0005_auto_20190917_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='articles_tags',
            field=models.ManyToManyField(to='unfrozen.Tag'),
        ),
        migrations.DeleteModel(
            name='TagArticle',
        ),
    ]
