# Generated by Django 3.0a1 on 2019-09-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unfrozen', '0007_tag_tag_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_articles',
        ),
    ]
